### ISSUE TITLE
lack of data_train/ROIs/[SUBJECT_ID].json

### ISSUE THREAD

**Issue by 6-dof** [HuthLab/semantic-decoding#1]
Hello, thank you for your share. Could you upload the data_train/ROIs file in which codes need [SUBJECT_ID].json?. It showed abscence of it when I estimated the word rate model following README.md. And it seems that there aren't any files like it in OpenNeuro.

**Comment by jtpacific** [comment]
Thanks for bringing this to our attention. We have uploaded a [new version](https://utexas.box.com/shared/static/3go1g4gcdar2cntjit2knz5jwr3mvxwe.zip) of `data_train` with the ROIs included.
