### ISSUE TITLE
Releasing data_train/ROIs/[SUBJECT_ID].json

### ISSUE THREAD

**Issue by vsubramaniam851** [HuthLab/semantic-decoding#2]
Wanted to follow-up on the previous issue. Could the ROI jsons be released? We would like to be able to train the word-rate models from scratch for our own individual analysis. I can't identify any similar file in the OpenNeuro release as well. 
Thank you!

**Comment by czlwang** [comment]
Hi! I thank the authors for releasing the code, but I'm also having the same issue.

**Comment by jtpacific** [comment]
Thanks for bringing this to our attention. We have uploaded a [new version](https://utexas.box.com/shared/static/3go1g4gcdar2cntjit2knz5jwr3mvxwe.zip) of `data_train` with the ROIs included.
