### ISSUE TITLE
How can I map those voxels to the cortical region? 

### ISSUE THREAD

**Issue by sjlljs176** [HuthLab/semantic-decoding#3]
Hello!

When I open the h5 files, the data of voxels have the shape(N, 81126).
But through the **pycortex** lib, I find that **.nii.gz have the shape(54, 84, 84).
The different shapes between them make me confused.

**Comment by dyhan316** [comment]
it's probably cuz not all the fMRI data are used (i.e. not all the brain voxels are used)

**Comment by jtpacific** [comment]
The h5 files contain proprocessed data, which are restricted to cortical voxels. You can find a mask of the cortical voxels at pycortex-db/[PARTICIPANT]/transforms/mask_thick.nii.gz.
