### ISSUE TITLE
Where is the sess_to_story.json?

### ISSUE THREAD

**Issue by 1994cxy** [HuthLab/semantic-decoding#5]
Thanks for your sharing. But I have some problems in running train_EM.py, the sess_to_story.json is missing. 
I found the sess_to_story.json in another repository [here](https://github.com/HuthLab/deep-fMRI-dataset/blob/eaaa5cd186e0222c374f58adf29ed13ab66cc02a/em_data/sess_to_story.json), but it seems doesn't fit with the default sessions in train_EM.py.

**Comment by dyhan316** [comment]
It think its in the data you download from openneuro

**Comment by jtpacific** [comment]
You can download the sess_to_story.json file here (https://utexas.box.com/shared/static/3go1g4gcdar2cntjit2knz5jwr3mvxwe.zip).
