### ISSUE TITLE
Dataset for fine-tuning GPT?

### ISSUE THREAD

**Issue by ShijiXiang1999** [HuthLab/semantic-decoding#6]
Thanks fot your fascinating and solid works. I wonder if you can provide your corpus comprising Reddit comments and other stories. Because I want to verify if changing to another LLM model affects the decoding performance. 
It's OK if the dataset is not available due to competing interests or patent pretection. I would appreciate it if you could help me with this. Thanks a lot.

**Comment by jtpacific** [comment]
Unfortunately we are not able to share the corpus as we do not have license to the Reddit comments. However any large text corpus should be sufficient, the main idea is just to expand the GPT vocabulary to include all of the words in the decoder vocabulary.
