### ISSUE TITLE
How to make .hf5 files as resp data.

### ISSUE THREAD

**Issue by miyucka621** [HuthLab/semantic-decoding#7]
Thank you for your exciting research results.I have a question.

 Is my understanding correct that  you used "derivative/preprocessed_data/*.hf5" as resp data? I wonder how to make these .hf5 files. A website（https://openneuro.org/datasets/ds004510/versions/1.1.0）stated that "preprocessed data: fully preprocessed data as described in previous works." but I don't know where to refer. 

I would appreciate it if you could give me some guidance.

**Comment by jtpacific** [comment]
Yes, we used the preprocessed responses. The data preprocessing steps are described in previous studies from our lab:

https://www.nature.com/articles/s41597-023-02437-z
https://www.nature.com/articles/nature17637
